#define GPIO_PROTECT 27
#define GPIO_RC_TRANSMIT 26

#define STACK_RC_TASK 8192
#define PRIORITY_RC_TASK 24
#define CORE_RC_TASK 1

#define STACK_HOMESPAN_TASK 8192
#define PRIORITY_HOMESPAN_TASK 1
#define CORE_HOMESPAN_TASK 0

#define MAX_CONNECTIONS_WEBSERVER 4
#define MAX_CONNECTIONS_HOMESPAN 8
